public class BasicPrograms4 {

    // Function for word count
    public static int wordscount(String word){
        if(word==null){
            return 0;
        }
        if(word.length()==0){
            return 0;
        }
        int countwords=0;
        char precharacter = word.charAt(0);
        for(int index=0;index<word.length();index++){
            char character = word.charAt(index);
            if(character==' '|| character=='\n' || character== '\t' || character=='\0' ){
                if(precharacter!=' '&& precharacter!='\n' && precharacter!= '\t' && precharacter!='\0' )
                countwords++;
            }
            precharacter=character;

        }
        return countwords+1;
    }

    // Function for converting decimal number to binary number
    public static void printbinary(int number){
        if(number<0){
            return;
        }
        int countbites = Integer.BYTES*8;
        
        int mask=1;
        mask=mask<<(countbites-2);
        while(mask>0){
            int result=number&mask;
            if(result==0){
                System.out.print("0");
            }
            else{
                System.out.print("1");
            }
            mask=mask>>1;
            }
        }

        // Function to remove whitespace from strings
        public static String removespaces(String sentence){
            StringBuilder newstring = new StringBuilder();
            for(int index=0;index<sentence.length();index++){
                if(sentence.charAt(index)!=' '){
                    newstring.append(sentence.charAt(index));
                }
                
            }
          String result = newstring.toString();
              return result;
           
        }

    
    
    public static void main(String[] args) {
        //System.out.println(wordscount("Report generated by     HealthCure Alzheimer's Detection System"));
        //printbinary(1);
       // printbinary(15);
        System.out.println(removespaces("Report generated by HealthCure Alzheimer's Detection System."));
    }
}
